apiVersion: v1
kind: Service
metadata:
  name: jbk-flask-service
  namespace: default
spec:
  selector:
    app: jbk-flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
